version: '2'
services:
    av-api:
        image: byuoitav/rpi-av-api:stage
        ports:
            - "8000:8000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
        network_mode: "host"
        restart: always
    crestron-control-microservice:
        image: byuoitav/rpi-crestron-control-microservice:stage
        ports:
            - "8004:8004"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
    pjlink-microservice:
        image: byuoitav/rpi-pjlink-microservice:stage
        ports:
            - "8005:8005"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - PJLINK_PORT=$PJLINK_PORT 
            - PJLINK_PASS=$PJLINK_PASS
        network_mode: "host"
        restart: always
    configuration-database-microservice:
        image: byuoitav/rpi-configuration-database-microservice:stage
        ports:
            - "8006:8006"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_USERNAME=$CONFIGURATION_DATABASE_USERNAME 
            - CONFIGURATION_DATABASE_PASSWORD=$CONFIGURATION_DATABASE_PASSWORD 
            - CONFIGURATION_DATABASE_HOST=$CONFIGURATION_DATABASE_HOST 
            - CONFIGURATION_DATABASE_PORT=$CONFIGURATION_DATABASE_PORT 
            - CONFIGURATION_DATABASE_NAME=$CONFIGURATION_DATABASE_NAME
        network_mode: "host"
        restart: always
    sony-control-microservice:
        image: byuoitav/rpi-sony-control-microservice:stage
        ports:
            - "8007:8007"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - SONY_TV_PSK=$SONY_TV_PSK
        network_mode: "host"
        restart: always
    london-audio-microservice:
        image: byuoitav/rpi-london-audio-microservice:stage
        ports:
            - "8009:8009"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
    cgi-microservice:
        image: byuoitav/rpi-cgi-microservice:stage
        ports:
            - "8010:8010"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
    pulse-eight-neo-microservice:
        build: byuoitav/rpi-pulse-eight-neo-microservice
        ports:
            - "8011:8011"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
    adcp-control-microservice:
        image: byuoitav/rpi-adcp-control-microservice:stage
        ports:
            - "8012:8012"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
    av-api-rpc:
        image: byuoitav/rpi-av-api-rpc:stage
        ports:
            - "8100:8100"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
        network_mode: "host"
        restart: always
    touchpanel-ui-microservice:
        image: byuoitav/rpi-touchpanel-ui-microservice:stage
        ports:
            - "8888:8888"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
    zeromq-proxy-microservice:
        image: byuoitav/rpi-zeromq-proxy-microservice:stage
        ports:
            - "7000:7000"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - PI_HOSTNAME=$PI_HOSTNAME
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
        network_mode: "host"
        restart: always
